# Chapter 3 - Numpy Basics

Main reference:<br>
- Chapter 4, Python for Data Analysis, by Wes McKinney
- Natural Language Processing with Classification and Vector Spaces, by DeepLearning.AI

Last edited: 05/16/2021

---

In this chapter, you will have the opportunity to remember some basic concepts about linear algebra and how to use them in Python. 

**Contents of this Notebook:**

- [Section 1. Introducing Numpy ndarray](#Section-1.-Introducing-Numpy-ndarray)
- [Section 2. Universal Functions: Fast Element-Wise Array Functions](#Section-2.-Universal-Functions:-Fast-Element-Wise-Array-Functions)
- [Section 3. Linear Algebra](#Section-3.-Linear-Algebra)


Numpy, short for Numerical Python, is one of the most used libraries in Python for arrays manipulation. It adds to Python a set of functions that allows us to operate on large multidimensional arrays with just a few lines. So if you were a MATLAB user, you would find some similar commands here.

Let us import the `numpy` library and assign the alias `np` for it. 

In [1]:
# %load_ext nb_black
import numpy as np  # The swiss knife of the data scientist.

<IPython.core.display.Javascript object>

# Section 1. Introducing Numpy ndarray

## Defining lists and numpy arrays

In [2]:
list1 = [1, 2, 3, 4]  # Define a python list. It looks like an np array
arr = np.array([1, 2, 3])  # Define a numpy array

<IPython.core.display.Javascript object>

Note the difference between a Python list and a NumPy array.

In [3]:
print(list1)
print(arr)

print(type(list1))
print(type(arr))

[1, 2, 3, 4]
[1 2 3]
<class 'list'>
<class 'numpy.ndarray'>


<IPython.core.display.Javascript object>

Numpy array is more efficient and faster than Python list.

In [4]:
my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 13.8 ms, sys: 9.06 ms, total: 22.8 ms
Wall time: 23.2 ms
CPU times: user 551 ms, sys: 158 ms, total: 709 ms
Wall time: 712 ms


<IPython.core.display.Javascript object>

## Algebraic operators on NumPy arrays vs. Python lists

One of the common beginner mistakes is to mix up the concepts of NumPy arrays and Python lists. Just observe the next example, where we add two objects of the two mentioned types. Note that the '+' operator on NumPy arrays perform an element-wise addition, while the same operation on Python lists results in a list concatenation. Be careful while coding. Knowing this can save many headaches.

In [5]:
print(arr + arr)
print(list1 + list1)

[2 4 6]
[1, 2, 3, 4, 1, 2, 3, 4]


<IPython.core.display.Javascript object>

It is the same as with the product operator, `*`. In the first case, we scale the vector, while in the second case, we concatenate three times the same list.

In [6]:
print(arr * 3)
print(list1 * 3)

[3 6 9]
[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


<IPython.core.display.Javascript object>

Be aware of the difference because, within the same function, both types of arrays can appear. <br>

**Numpy arrays are designed for numerical and matrix operations, while lists are for more general purposes.**

## Matrix or Array of Arrays (ndarray)

In linear algebra, a matrix is a structure composed of m rows by n columns. That means each row must have the same number of columns. We can create a matrix:
* Creating an array of arrays using `np.array`. 
* Creating a matrix using `np.matrix` (still available but might be removed soon).

NumPy arrays or lists can be used to initialize a matrix, but the resulting matrix will be composed of NumPy arrays only.

In [7]:
npmatrix1 = np.array([arr, arr, arr])  # Matrix initialized with NumPy arrays
npmatrix2 = np.array([list1, list1, list1])  # Matrix initialized with lists
npmatrix3 = np.array([arr, [1, 1, 1], arr])  # Matrix initialized with both types

print(npmatrix1)
print(npmatrix2)
print(npmatrix3)
print(type(npmatrix3))

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1 2 3]
 [1 1 1]
 [1 2 3]]
<class 'numpy.ndarray'>


<IPython.core.display.Javascript object>

However, when defining a matrix, be sure that all the rows contain the same number of elements. Otherwise, the linear algebra operations could lead to unexpected results.

Analyze the following two examples:

In [8]:
# Example 1:

okmatrix = np.array([[1, 2], [3, 4]])  # Define a 2x2 matrix
print(okmatrix)  # Print okmatrix
print(okmatrix * 2)  # Print a scaled version of okmatrix

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


<IPython.core.display.Javascript object>

In [9]:
# Example 2:

badmatrix = np.array(
    [[1, 2], [3, 4], [5, 6, 7]]
)  # Define a matrix. Note the third row contains 3 elements

print(badmatrix)  # Print the malformed matrix
print(badmatrix * 2)  # It is supposed to scale the whole matrix

[list([1, 2]) list([3, 4]) list([5, 6, 7])]
[list([1, 2, 1, 2]) list([3, 4, 3, 4]) list([5, 6, 7, 5, 6, 7])]


<IPython.core.display.Javascript object>

In [10]:
type(badmatrix * 2)

numpy.ndarray

<IPython.core.display.Javascript object>

In [11]:
okmatrix.shape

(2, 2)

<IPython.core.display.Javascript object>

In [12]:
matrix1 = np.array([[1, 2], [3, np.nan]])

<IPython.core.display.Javascript object>

In [13]:
matrix1.shape

(2, 2)

<IPython.core.display.Javascript object>

In [14]:
arr = np.array([[1], [2], [3]])
arr.shape

(3, 1)

<IPython.core.display.Javascript object>

## Shape and Type

Every array has a `shape`, a tuple indicating the size of each dimension, and a `dtype`, an object describing
the data type of the array.

In [15]:
arr = np.array([1, 2, 3])
arr.shape

(3,)

<IPython.core.display.Javascript object>

In [16]:
arr.ndim

1

<IPython.core.display.Javascript object>

Note that `(3,)` ndarray is different with `(3,1)` ndarray. Using `reshape` can change the shape.

In [17]:
arr.reshape(3, 1)

# arr.reshape(3, 1).ndim

array([[1],
       [2],
       [3]])

<IPython.core.display.Javascript object>

In [18]:
arr.reshape(3, 1) + 2 * np.ones((3, 1))

array([[3.],
       [4.],
       [5.]])

<IPython.core.display.Javascript object>

In [19]:
arr.dtype

dtype('int64')

<IPython.core.display.Javascript object>

## Creating More Arrays: 0s, 1s, random number, and evenly spaced values

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

<IPython.core.display.Javascript object>

In [21]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

<IPython.core.display.Javascript object>

In [22]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

<IPython.core.display.Javascript object>

To initialize a NumPy array with NaN values in Python, we need to create an uninitialized array and assign to all entries at once.

In [23]:
np.empty((3, 3))

array([[ 1.72723371e-077, -4.32950213e-311,  2.41907520e-312],
       [ 2.54639495e-312,  2.44029516e-312,  2.05833592e-312],
       [ 2.14321575e-312,  2.35541533e-312,  2.18565567e-312]])

<IPython.core.display.Javascript object>

In [24]:
arr_nan = np.empty((3, 3))
arr_nan[:] = np.nan
arr_nan

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

<IPython.core.display.Javascript object>

In [25]:
# Fix the seed
np.random.seed(123)

# Return a sample (or samples) from the “standard normal” distribution.
data = np.random.randn(2, 3)
data

array([[-1.0856306 ,  0.99734545,  0.2829785 ],
       [-1.50629471, -0.57860025,  1.65143654]])

<IPython.core.display.Javascript object>

In [26]:
# Values are generated within the half-open interval [start, stop)
# (in other words, the interval including start but excluding stop).

np.arange(0, 3, 0.3)


array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

<IPython.core.display.Javascript object>

## Indexing elements in a ndarray
* `axis 0`: rows
* `aixs 1`: columns
<img src="images/indexing.png" alt="indexing" width="500"/>

In [27]:
arr3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr3x3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


<IPython.core.display.Javascript object>

In [28]:
arr3x3[0, 1]

2

<IPython.core.display.Javascript object>

## Indexing with Slices
<img src="images/arrayslicing.png" alt="arrayslicing" width="500"/>

In [29]:
print(arr3x3)
arr3x3[:2, 1:]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[2, 3],
       [5, 6]])

<IPython.core.display.Javascript object>

## Arithmetic with Numpy Arrays

Any arithmetic operations between equal-size arrays applies the operation element-wise.

In [30]:
arr2x2 = np.array([[1, 2], [3, 4]])

print(arr2x2)

[[1 2]
 [3 4]]


<IPython.core.display.Javascript object>

In [31]:
# Add two sum compatible matrices
result1 = arr2x2 + arr2x2
print(result1)

# Subtract two sum compatible matrices. This is called the difference vector
result2 = arr2x2 - arr2x2
print(result2)

[[2 4]
 [6 8]]
[[0 0]
 [0 0]]


<IPython.core.display.Javascript object>

The product operator `*` when used on arrays or matrices indicates element-wise multiplications.

**Do not confuse it with the dot product.**

In [32]:
result = arr2x2 * arr2x2  # Multiply each element by itself
print(result)

[[ 1  4]
 [ 9 16]]


<IPython.core.display.Javascript object>

Operations can be performed between arrays and arrays or between arrays and scalars.

In [33]:
result = arr2x2 * 2.0 + 1.0  # For each element in the matrix, multiply by 2 and add 1
print(result)

[[3. 5.]
 [7. 9.]]


<IPython.core.display.Javascript object>

## Transpose a matrix

In linear algebra, the transpose of a matrix is an operator that flips a matrix over its diagonal, i.e., the transpose operator switches the row and column indices of the matrix producing another matrix. If the original matrix dimension is m by n, the resulting transposed matrix will be n by m.

**T** denotes the transpose operations with NumPy matrices.

In [34]:
arr3x2 = np.array([[1, 2], [3, 4], [5, 6]])  # Define a 3x2 matrix
print("Original matrix 3 x 2")
print(arr3x2)
print("Transposed matrix 2 x 3")
print(arr3x2.T)

Original matrix 3 x 2
[[1 2]
 [3 4]
 [5 6]]
Transposed matrix 2 x 3
[[1 3 5]
 [2 4 6]]


<IPython.core.display.Javascript object>

However, note that the transpose operation does not affect 1D arrays.

In [35]:
nparray = np.array([1, 2, 3, 4])  # Define an array
print("Original array")
print(nparray)
print("Transposed array")
print(nparray.T)

Original array
[1 2 3 4]
Transposed array
[1 2 3 4]


<IPython.core.display.Javascript object>

In [36]:
nparray == nparray.T

array([ True,  True,  True,  True])

<IPython.core.display.Javascript object>

perhaps in this case you wanted to do:

In [37]:
nparray = np.array(
    [[1, 2, 3, 4]]
)  # Define a 1 x 4 matrix. Note the 2 level of square brackets

print("Original array")
print(nparray)
print("Transposed array")
print(nparray.T)

Original array
[[1 2 3 4]]
Transposed array
[[1]
 [2]
 [3]
 [4]]


<IPython.core.display.Javascript object>

## Sums by rows or columns

Another general operation performed on matrices is the sum by rows or columns.
Just as we did for the function norm, the **axis** parameter controls the form of the operation:
* **axis=0** means to sum the elements of each column together. 
* **axis=1** means to sum the elements of each row together.

In [38]:
arr2 = np.array([[1, -1], [2, -2], [3, -3]])  # Define a 3 x 2 matrix.

sumByCols = np.sum(arr2, axis=0)  # Get the sum for each column. Returns 2 elements
sumByRows = np.sum(arr2, axis=1)  # get the sum for each row. Returns 3 elements

print(arr2)
print("Sum by columns: ")
print(sumByCols)
print("Sum by rows:")
print(sumByRows)

[[ 1 -1]
 [ 2 -2]
 [ 3 -3]]
Sum by columns: 
[ 6 -6]
Sum by rows:
[0 0 0]


<IPython.core.display.Javascript object>

## Get the mean by rows or columns

As with the sums, one can get the **mean** by rows or columns using the **axis** parameter. Just remember that the mean is the sum of the elements divided by the length of the vector.

In [39]:
arr2 = np.array(
    [[1, -1], [2, -2], [3, -3]]
)  # Define a 3 x 2 matrix. Chosen to be a matrix with 0 mean

mean = np.mean(arr2)  # Get the mean for the whole matrix
meanByCols = np.mean(arr2, axis=0)  # Get the mean for each column. Returns 2 elements

meanByRows = np.mean(arr2, axis=1)  # get the mean for each row. Returns 3 elements

print(arr2)
print("Matrix mean: ")
print(mean)
print("Mean by columns: ")
print(meanByCols)
print("Mean by rows:")
print(meanByRows)

[[ 1 -1]
 [ 2 -2]
 [ 3 -3]]
Matrix mean: 
0.0
Mean by columns: 
[ 2. -2.]
Mean by rows:
[0. 0. 0.]


<IPython.core.display.Javascript object>

Note that some operations can be performed using static functions like `np.sum()` or `np.mean()`, or by using the inner functions of the array

In [40]:
arr3 = np.array([[1, 3], [2, 4], [3, 5]])  # Define a 3 x 2 matrix.

mean1 = np.mean(arr3)  # Static way (recommended)
mean2 = arr3.mean()  # Dinamic way

print(mean1, " == ", mean2)

3.0  ==  3.0


<IPython.core.display.Javascript object>

Even if they are equivalent, we recommend the use of **the static way** always.

---

# Section 2. Universal Functions: Fast Element-Wise Array Functions

A universal function, or *ufunc*, is a function that performs element-wise operations on data in ndarrays

In [41]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<IPython.core.display.Javascript object>

In [42]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

<IPython.core.display.Javascript object>

<img src="images/ufunc.png" alt="ufunc" width="800"/>

---

## Section 3. Linear Algebra

## The dot product between arrays

Multiplying two two-dimensional arrays with * is an element-wise product instead of a matrix dot product.

In Numpy, there is a function `dot`, both an array method and a function in the numpy namespace, for matrix multiplication


In [43]:
X = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])  # Define an matrix 2x3
Y = np.array([[6.0, 23.0], [-1, 7], [8, 9]])  # Define an matrix 3x2

flavor0 = X.dot(Y)  # normal way
print(flavor0)

flavor1 = np.dot(X, Y)  # Equivalent and recommended way
print(flavor1)

flavor2 = (X @ Y)  
# Geeks way: @ symbol works as an infix operator that performs matrix multiplication
print(flavor2)


[[ 28.  64.]
 [ 67. 181.]]
[[ 28.  64.]
 [ 67. 181.]]
[[ 28.  64.]
 [ 67. 181.]]


<IPython.core.display.Javascript object>

**I strongly recommend using np.dot, since it is the only method that accepts arrays and lists without problems**

In [44]:
norm1 = np.dot(np.array([1, 2]), np.array([3, 4]))  # Dot product on nparrays
norm2 = np.dot([1, 2], [3, 4])  # Dot product on python lists
norm3 = np.dot([1, 2], np.array([3, 4]))

print(norm1, "=", norm2, "=", norm3)

11 = 11 = 11


<IPython.core.display.Javascript object>

### Broadcasting

NumPy operations are usually done on pairs of arrays on an element-by-element basis.

[NumPy’s broadcasting rule](https://numpy.org/doc/stable/user/basics.broadcasting.html) relaxes this constraint when the arrays’ shapes meet certain constraints. 

In [45]:
# Example 1
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])

a * b

array([2., 4., 6.])

<IPython.core.display.Javascript object>

In [46]:
# Example 2
a = np.array([1.0, 2.0, 3.0])
b = 2.0

a * b

array([2., 4., 6.])

<IPython.core.display.Javascript object>

**General Broadcasting Rules**
When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when

1. they are equal, or

2. one of them is 1

In [47]:
# Example
arr2x2 = np.array([[1, 2], [3, 4]])

arr2x2

array([[1, 2],
       [3, 4]])

<IPython.core.display.Javascript object>

In [48]:
result = arr2x2 + np.array([[1, 2]])  # Broadcasting

print(result)

[[2 4]
 [4 6]]


<IPython.core.display.Javascript object>

In [49]:
result = arr2x2 + np.array([[1, 2]]).T  # Broadcasting

print(result)

[[2 3]
 [5 6]]


<IPython.core.display.Javascript object>

In [50]:
np.array([[1, 2]]) + arr2x2

array([[2, 4],
       [4, 6]])

<IPython.core.display.Javascript object>

In [51]:
# np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) + np.array([[1, 2]])

<IPython.core.display.Javascript object>

## `numpy.linalg` functions
A standard set of matrix decompositions and operations.


In [52]:
X = np.array([[-6, 3], [4, 5]])

np.linalg.inv(X)

array([[-0.11904762,  0.07142857],
       [ 0.0952381 ,  0.14285714]])

<IPython.core.display.Javascript object>

In [53]:
np.linalg.eig(X)

(array([-7.,  6.]),
 array([[-0.9486833 , -0.24253563],
        [ 0.31622777, -0.9701425 ]]))

<IPython.core.display.Javascript object>

In [54]:
w, v = np.linalg.eig(X)

<IPython.core.display.Javascript object>

Note: The normalized (unit “length”) eigenvectors, such that the column `v[:,i]` is the eigenvector corresponding to the eigenvalue `w[i]`.

<img src="images/la.png" alt="la" width="800"/>

---

#### Exercise 1

Compute the [euclidean distance](https://en.wikipedia.org/wiki/Euclidean_distance) between arrays p and q, with `np.square()`, `np.sum()`, and `np.sqrt()` functions.


$$d(p, q) = \sqrt{\sum^{n}_{i=1} (p_i - q_i)^2}$$

In [55]:
p = np.array((1, 2, 3))
q = np.array((2, 3, 4))

# insert your code here
euc_dist = None


print(euc_dist)

None


<IPython.core.display.Javascript object>

<details><summary>Click here for the solution</summary>

```python
euc_dist = np.sqrt(np.sum(np.square(p - q)))
    
```

</details>

#### Exercise 2

Compute the [euclidean distance](https://en.wikipedia.org/wiki/Euclidean_distance) between arrays p and q, with `np.dot()` and `np.sqrt()` functions.

$$d(p, q) = \sqrt{\sum^{n}_{i=1} (p_i - q_i)^2}$$

In [56]:
p = np.array((1, 2, 3))
q = np.array((2, 3, 4))

# insert your code here
euc_dist = None

print(euc_dist)

None


<IPython.core.display.Javascript object>

<details><summary>Click here for the solution</summary>

```python
euc_dist = np.sqrt(np.dot((p - q).T, (p - q)))

```

</details>

#### Exercise 3

Compute the [euclidean distance](https://en.wikipedia.org/wiki/Euclidean_distance) between arrays p and q, with [`numpy.linalg.norm()`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html) function.


$$d(p, q) = \sqrt{\sum^{n}_{i=1} (p_i - q_i)^2}$$

In [57]:
p = np.array((1, 2, 3))
q = np.array((2, 3, 4))

# insert your code here
euc_dist = None

print(euc_dist)

None


<IPython.core.display.Javascript object>

<details><summary>Click here for the solution</summary>

```python
euc_dist = np.linalg.norm(p - q)
```

</details>